app: gyrfalcon
component: express
name: api

inputs:
  # Express application source code.
  src: ./
  # Permissions required for the AWS Lambda function to interact with other resources
  roleName: ${output:permissions.name}
  # Enable this when you want to set a custom domain.
  domain: api.${env:domain}
